openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
  description: API for managing products.
servers:
  - url: http://localhost:8080/
    description: Local server

paths:
  /products:
    post:
      summary: Create a New Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Product Created Successfully
      x-events:
        emits:
          - ProductCreated
          - LowStockWarning

    get:
      summary: List All the Products
      responses:
        "200":
          description: Product List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /products/{id}:
    put:
      summary: Update a Product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "200":
          description: Product updated
      x-events:
        emits:
          - ProductUpdated
          - LowStockWarning

    delete:
      summary: delete a product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product Deleted
      x-events:
        emits:
          - ProductDeleted

  /events/stream:
    get:
      summary: Low-Stock Events (SSE)
      responses:
        "200":
          description: Stream of events
          content:
            text/event-stream:
              schema:
                type: string
      x-events:
        receives:
          - LowStockWarning

  /events/sns-endpoint:
    post:
      summary: AWS SNS Notification Endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: receipt of SNS message
      x-events:
        receives:
          - SubscriptionConfirmation
          - LowStockWarning

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "64f6d2c3e4d3c8a8d9b4f567"
        sellerId:
          type: string
          example: "seller-123"
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        quantity:
          type: integer
        imageUrl:
          type: string
          format: uri
          example: "https://s3.amazonaws.com/bucketname/file.png"
        category:
          $ref: "#/components/schemas/Category"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductInput:
      type: object
      properties:
        sellerId:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        quantity:
          type: integer
        imageUrl:
          type: string
          format: uri
        category:
          $ref: "#/components/schemas/Category"
      required:
        - sellerId
        - name
        - description
        - price
        - quantity
        - category

    Category:
      type: string
      enum:
        - ELECTRONICS
        - FASHION
        - HOME
        - BOOKS
        - TOYS
